# Generated by Django 3.2 on 2021-05-19 21:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')],
                    default='P',
                    max_length=1
                    )),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('date_written', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
