# Generated by Django 3.2 on 2021-04-19 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                (
                    'apartment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='apt_connection',
                        to='users.apartment'
                    )
                ),
                (
                    'seeker',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='seeker_connection',
                        to='users.seeker'
                    )
                ),
            ],
            options={
                'unique_together': {('apartment', 'seeker')},
            },
        ),
    ]
