# Generated by Django 3.1.7 on 2021-04-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('contacts', '0001_initial'),
        ('seekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='apt_connection', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='connection',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='seeker_connection', to='seekers.seeker'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('apartment', 'seeker')},
        ),
    ]
