# Generated by Django 3.1.7 on 2021-04-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to. \
                    A user will get all permissions granted to each of their groups.',
                related_name='user_set',
                related_query_name='user',
                to='auth.Group',
                verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePosted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('rentPricePerMonth', models.IntegerField()),
                ('numOfRoomates', models.IntegerField()),
                ('numOfRooms', models.IntegerField()),
                ('startDate', models.DateField()),
                ('content', models.TextField(blank=True)),
                ('isRelevant', models.BooleanField(blank=True, default=True)),
                ('city', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='city_apartments',
                    to='users.city')),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='owner_apartments',
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
