# Generated by Django 3.2 on 2021-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_test_data_apartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.'
                                         'A user will get all permissions granted to each of their groups.',
                                         related_name='user_set', related_query_name='user', to='auth.Group',
                                         verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.TextField(blank=True, default='../../static/img/user-account.png'),
        ),
    ]
