# Generated by Django 3.2 on 2021-04-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20210422_0602'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_auto_20210419_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='city_seekers',
                to='apartments.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to. \
                    A user will get all permissions granted to each of their groups.',
                related_name='user_set',
                related_query_name='user',
                to='auth.Group',
                verbose_name='groups'),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
