# Generated by Django 3.2 on 2021-04-21 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('rent', models.IntegerField()),
                ('num_of_roomates', models.IntegerField()),
                ('num_of_rooms', models.IntegerField()),
                ('start_date', models.DateField()),
                ('about', models.TextField(blank=True)),
                ('is_relevant', models.BooleanField(blank=True, default=True)),
                ('image_url', models.TextField(blank=True)),
                ('city', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='city_apartments',
                    to='apartments.city')),
                ('owner', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
