# Generated by Django 3.2 on 2021-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image_url',
            field=models.TextField(blank=True, default='../../static/img/default_apartment.png'),
        ),
    ]
