APARTMENT_ABOUT = ["Hey there I'm looking for roomates!",
                   "Best apartment in the city!",
                   "Looking for female roomates!",
                   "Relevant only for 30+ years old!",
                   "We love CATS!",
                   "Pizza it's a must!",
                   "Maccabi or nothing",
                   "We are geeks!",
                   "Student zone",
                   "Lets go! JOIN US",
                   "Unicorn lovers",
                   "Hey there"
                   "We are looking for you",
                   "Lebron is better than MJ",
                   "Lets have some fun",
                   "Close to the beach",
                   "Pink floyd",
                   "The dark side of the city",
                   "Our apartment speak for iteself",
                   "Our balcony is a dream", ]

SEEKER_ABOUT = ["Hey there I'm looking for a new apartment!",
                "I'm a student",
                "Ride or Die",
                "Let me entertain you",
                "I'm 32 years old",
                "looking for vegan frineds",
                "Lets party",
                "I love pizza",
                "Hey! I'm 2.03 CM",
                "Hey! there I'm a cool guy",
                "shh.. Lets meet",
                "I can't tell you.",
                "Sushi each friday!",
                "Hello, Nice to meet",
                "I'm a Unicorn",
                "I'm a gamer",
                "Hello. I'm looking to join ASAP",
                "Hey boys and girls",
                "I love chess",
                "Good vibes only", ]
