CITIES_NAMES_LIST = [
    ('Jerusalem'),
    ('Tel Aviv'),
    ('Haifa'),
    ('Ashdod'),
    ('Rishon LeZiyyon'),
    ('Petah Tiqwa'),
    ('Beersheba'),
    ('Netanya'),
    ('Holon'),
    ('Bnei Brak'),
    ('Rehovot'),
    ('Bat Yam'),
    ('Ramat Gan'),
    ('Ashkelon'),
    ('Jaffa'),
    ('Modiin'),
    ('Herzliya'),
    ('Kfar Saba'),
    ('Raanana'),
    ('Hadera'),
    ('Bet Shemesh'),
    ('Lod'),
    ('Nazareth'),
    ('Atlit'),
    ('Ramla'),
    ('Nahariyya'),
    ('Qiryat Ata'),
    ('Givatayim'),
    ('Qiryat Gat'),
    ('Acre'),
    ('Eilat'),
    ('Afula'),
    ('Karmiel'),
    ('Hod HaSharon'),
    ('Umm el Fahm'),
    ('Tiberias'),
    ('Qiryat Mozqin'),
    ('Qiryat Yam'),
    ('Rosh HaAyin'),
    ('Ness Ziona'),
    ('Qiryat Bialik'),
    ('Ramat HaSharon'),
    ('Dimona'),
    ('Taiyiba'),
    ('Yavne'),
    ('Or Yehuda'),
    ('Qiryat Shemona'),
    ('Kefar Yona'),
    ('Shoham'),
    ('Pardesiya'),
]
