HOBBIES_LIST = [
    ('Reading'),
    ('Watching TV'),
    ('Family Time'),
    ('Movies'),
    ('Fishing'),
    ('Computer'),
    ('Gardening'),
    ('Painting'),
    ('Walking'),
    ('Exercise'),
    ('Listening to Music'),
    ('Entertaining'),
    ('Hunting'),
    ('Team Sports'),
    ('Shopping'),
    ('Traveling'),
    ('Sleeping'),
    ('Socializing'),
    ('Sewing'),
    ('Golf'),
    ('Church Activities'),
    ('Relaxing'),
    ('Playing Music'),
    ('Housework'),
    ('Crafts'),
    ('Watching Sports'),
    ('Bicycling'),
    ('Playing Cards'),
    ('Hiking'),
    ('Cooking'),
    ('Eating Out'),
    ('Dating Online'),
    ('Swimming'),
    ('Camping'),
    ('Skiing'),
    ('Working on Cars'),
    ('Writing'),
    ('Boating'),
    ('Motorcycling'),
    ('Animal Care'),
    ('Bowling'),
    ('Snooker'),
    ('Running'),
    ('Diving'),
    ('Watching Netflix'),
    ('Gaming'),
    ('CTFs'),
    ('Basketball'),
    ('Sports fan'),
    ('Solving problems'),
]
