STREETS_LIST = [
    'Union Street',
    'South Street',
    'Monroe Drive',
    'Grove Avenue',
    'Inverness Drive',
    'Oak Avenue',
    'Chestnut Street',
    'Broad Street West',
    '4th Street South',
    'Meadow Lane',
    'Willow Avenue',
    'Locust Street',
    'Deerfield Drive',
    'Canterbury Road',
    'Lexington Court',
    'Cedar Avenue',
    'Queen Street',
    'Front Street South',
    'Glenwood Avenue',
    'Park Place',
    '3rd Street',
    'Manor Drive',
    'Woodland Road',
    'Pennsylvania Avenue',
    'Main Street West',
    'Fulton Street',
    'Myrtle Street',
    'Devonshire Drive',
    'Colonial Avenue',
    'Hillside Avenue',
    'Pheasant Run',
    'Grant Avenue',
    'Main Street',
    'Elizabeth Street',
    '2nd Street East',
    'Taylor Street',
    'Prospect Street',
    'Wall Street',
    'Depot Street',
    'King Street',
    'Woodland Drive',
    'Pin Oak Drive',
    'Roosevelt Avenue',
    'Bridle Court',
    'Holly Drive',
    'Route 6',
    'Andover Court',
    'Bridge Street',
    'Summer Street',
    'Lafayette Avenue',
    'Warren Avenue',
    'Mulberry Street',
    'Cedar Court',
    'Aspen Drive',
    'Center Street',
    'York Street',
    'State Street East',
    'Grant Street',
    'Jefferson Avenue',
    'Cypress Court',
    'Oxford Road',
    'Bay Street',
    'Pine Street',
    'Belmont Avenue',
    'Franklin Court',
    'Morris Street',
    '3rd Street West',
    'Lexington Drive',
    '5th Street West',
    'Church Street',
    'Highland Avenue',
    'Hawthorne Avenue',
    'Strawberry Lane',
    'Dogwood Lane',
    'Sycamore Street',
    'Olive Street',
    'Windsor Drive',
    'Summit Street',
    '8th Street',
    '9th Street West',
    'Broadway',
    'River Road',
    '4th Street North',
    '5th Avenue',
    'Orchard Street',
    'Cedar Lane',
    'Brandywine Drive',
    'Madison Street',
    'Country Club Road',
    'North Street',
    'Circle Drive',
    '4th Street',
    'Route 41',
    'Route 11',
    'Lincoln Avenue',
    'Harrison Avenue',
    'Spring Street',
    'Maple Lane',
    'Valley Drive',
    'Cambridge Road',
]
